package mensajes;

public enum messageType {
	CONEXION,
	CONFIRMACION_CONEXION,
	LISTA_USUARIOS,
	CONFIRMACION_LISTA,
	CERRAR_CONEXION,
	CONFIRMACION_CERRAR,
	PEDIR_FICHERO,
	EMITIR_FICHERO,
	PREPARADO_CLIENTE_SERVIDOR,
	PREPARADO_SERVIDOR_CLIENTE,
	ADD_FILE,
	CONFIRMACION_ADD
}
